# Generated by Django 3.2.13 on 2022-04-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoT_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_no', models.IntegerField()),
                ('Device_id', models.CharField(max_length=50)),
                ('Device_name', models.CharField(max_length=500)),
                ('tempt_sensor', models.CharField(max_length=10)),
                ('press_sensor', models.CharField(max_length=10)),
            ],
        ),
    ]
